table = "\
    <table class='table table-bordered table-hover table-condensed table-responsive'>\
        <tr>\
        <h3 class='text-center'>2016级绩点与成绩换算关系</h3>\
        </tr>\
        <tr>\
            <td>百分制成绩</td>\
            <td>100-90</td>\
            <td>89-85</td>\
            <td>84-81</td>\
            <td>80-78</td>\
            <td>77-75</td>\
            <td>74-72</td>\
            <td>71-68</td>\
            <td>67-65</td>\
            <td>64-63</td>\
            <td>62-60</td>\
            <td>59-40</td>\
        </tr>\
        <tr>\
            <td>五级成绩</td>\
            <td>A</td>\
            <td>A-</td>\
            <td>B+</td>\
            <td>B</td>\
            <td>B-</td>\
            <td>C+</td>\
            <td>C</td>\
            <td>C-</td>\
            <td>D+</td>\
            <td>D</td>\
            <td>F+</td>\
        </tr>\
        <tr>\
            <td>绩点</td>\
            <td>4.0</td>\
            <td>3.7</td>\
            <td>3.3</td>\
            <td>3.0</td>\
            <td>2.7</td>\
            <td>2.3</td>\
            <td>2.0</td>\
            <td>1.7</td>\
            <td>1.3</td>\
            <td>1.0</td>\
            <td>0</td>\
        </tr>\
    </table>"

$('#score').html(table)